service: user

frameworkVersion: "3"

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x

  environment:
    AUTH0_MANAGEMENT_CLIENT_SECRET: "${env:AUTH0_MANAGEMENT_CLIENT_SECRET}"
    CREATURE_CHESS_FAUNA_KEY: "${env:CREATURE_CHESS_FAUNA_KEY}"

  region: eu-west-1

functions:
  GetCurrentUser:
    handler: handler.getCurrentUser

    events:
      - http:
          path: user/current/
          method: get
  UpdateCurrentUser:
    handler: handler.updateCurrentUser

    events:
      - http:
          path: user/current/
          method: patch

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
      - superagent-proxy
    target: node14
    platform: node
    concurrency: 10

package:
  individually: true

resources:
  Outputs:
    GetCurrentUserQualifiedArn:
      Export:
        Name: GetCurrentUserQualifiedArn
      Value:
        Ref: GetCurrentUserLambdaFunction
    UpdateCurrentUserQualifiedArn:
      Export:
        Name: UpdateCurrentUserQualifiedArn
      Value:
        Ref: UpdateCurrentUserLambdaFunction
    UserServiceApiGatewayQualifiedArn:
      Export:
        Name: UserServiceApiGatewayQualifiedArn
      Value:
        Fn::Join:
          [
            ":",
            [
              "arn:aws:execute-api",
              { "Ref": "AWS::Region" },
              { "Ref": "AWS::AccountId" },
              { "Ref": "ApiGatewayRestApi" },
            ],
          ]
