version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/local-dev/Dockerfile
    volumes:
      - ./nginx/local-dev/nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/local-dev/nginx/access.log:/etc/nginx/access_log.log
    ports:
      - 8080:8080
  web-menu:
    build:
      context: .
      dockerfile: apps/Dockerfile
      args:
        - APP_DIR=web-menu
    ports:
      - "3000"
  server-game:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - DISCORD_BOT_TOKEN
      - NODE_ENV=development
    build:
      context: .
      dockerfile: apps/Dockerfile
      args:
        - APP_DIR=server-game
    ports:
      - "3000"
