version: "3.8"
services:
  # we use faunadb dev for local development
  faunadb:
    image: fauna/faunadb
    volumes:
      - ./.faunadb/lib/:/var/lib/faunadb
      - ./.faunadb/log/:/var/log/faunadb
    ports:
      - 8443:8443
      - 8084:8084
    # TODO (James) fix this healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443"]
      interval: 30s
      timeout: 5s
      retries: 5
  # in `docker-compose.local`, manually apply faunadb config for the dev db above
  server-game:
    environment:
      - CREATURE_CHESS_FAUNA_KEY=secret
      - CREATURE_CHESS_FAUNA_DOMAIN=faunadb
      - CREATURE_CHESS_FAUNA_SCHEME=http
      - CREATURE_CHESS_FAUNA_PORT=8443
    depends_on:
      - faunadb
    restart: always
  # in `docker-compose.local`, manually apply faunadb config for the dev db above
  server-info:
    environment:
      - CREATURE_CHESS_FAUNA_KEY=secret
      - CREATURE_CHESS_FAUNA_DOMAIN=faunadb
      - CREATURE_CHESS_FAUNA_SCHEME=http
      - CREATURE_CHESS_FAUNA_PORT=8443
    depends_on:
      - faunadb
    restart: always
