version: "3.8"
services:
  server-game:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - DISCORD_BOT_TOKEN
    build:
      context: .
      dockerfile: ./Dockerfile.server-game
    ports:
      - "3000:3000"
  server-info:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - AUTH0_MANAGEMENT_CLIENT_SECRET
    build:
      context: .
      dockerfile: ./Dockerfile.server-info
    ports:
      - "3001:3000"
