version: "3.8"
services:
  # in `docker-compose.local`, manually apply faunadb config for the dev db above
  server-game:
    environment:
      - CREATURE_CHESS_FAUNA_KEY=secret
      - CREATURE_CHESS_FAUNA_DOMAIN=faunadb
      - CREATURE_CHESS_FAUNA_SCHEME=http
      - CREATURE_CHESS_FAUNA_PORT=8443
    restart: always
  # in `docker-compose.local`, manually apply faunadb config for the dev db above
  server-info:
    environment:
      - CREATURE_CHESS_FAUNA_KEY=secret
      - CREATURE_CHESS_FAUNA_DOMAIN=faunadb
      - CREATURE_CHESS_FAUNA_SCHEME=http
      - CREATURE_CHESS_FAUNA_PORT=8443
    restart: always
