FROM node:12-alpine AS node

FROM node AS server-deps

WORKDIR /usr/src/cc-server

# root dependencies

COPY lerna.json ./
COPY package.json package-lock.json ./

# packages

COPY packages/ ./packages/

RUN npm ci --loglevel notice

COPY tsconfig.json .
COPY scripts/ ./scripts/

FROM server-deps AS builder

RUN npm run build

FROM builder as server

EXPOSE 3000

CMD [ "node", "packages/@creature-chess/server-game/lib/index.js", "3000" ]
