version: "3.8"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/local-dev/Dockerfile
    volumes:
      - ./nginx/local-dev/nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/local-dev/nginx/access.log:/etc/nginx/access_log.log
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web-menu
      - server-game
      - server-info
  web-menu:
    environment:
      - DISCORD_BOT_TOKEN
      - AUTH0_DOMAIN
      - AUTH0_SPA_CLIENT_ID
      - CREATURE_CHESS_APP_URL
      - GAME_SERVER_URL
      - API_INFO_URL
      - CREATURE_CHESS_IMAGE_URL
      - NODE_ENV=development
    build:
      context: .
      dockerfile: apps/Dockerfile
      args:
        - APP_DIR=web-menu
    ports:
      - "3000"
  server-game:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - CREATURE_CHESS_FAUNA_DOMAIN
      - CREATURE_CHESS_FAUNA_SCHEME
      - CREATURE_CHESS_FAUNA_PORT
      - DISCORD_BOT_TOKEN
      - AUTH0_DOMAIN
      - AUTH0_SPA_CLIENT_ID
      - AUTH0_MACHINE_TO_MACHINE_CLIENT_ID
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - CREATURE_CHESS_APP_URL
      - API_INFO_URL
      - CREATURE_CHESS_IMAGE_URL
      - NODE_ENV=development
    build:
      context: .
      dockerfile: apps/Dockerfile
      args:
        - APP_DIR=server-game
    ports:
      - "3000"
    restart: always
  server-info:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - CREATURE_CHESS_FAUNA_DOMAIN
      - CREATURE_CHESS_FAUNA_SCHEME
      - CREATURE_CHESS_FAUNA_PORT
      - AUTH0_DOMAIN
      - AUTH0_SPA_CLIENT_ID
      - AUTH0_MACHINE_TO_MACHINE_CLIENT_ID
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - CREATURE_CHESS_APP_URL
      - NODE_ENV
    build:
      context: .
      dockerfile: apps/Dockerfile
      args:
        - APP_DIR=server-info
    ports:
      - "3000"
    restart: always
