version: "3.8"
services:
  faunadb:
    image: fauna/faunadb
    volumes:
      - ./.faunadb/lib/:/var/lib/faunadb
      - ./.faunadb/log/:/var/log/faunadb
    ports:
      - 8443:8443
      - 8084:8084
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443"]
      interval: 30s
      timeout: 5s
      retries: 5
  web-menu:
    depends_on:
      - faunadb
  server-game:
    environment:
      - CREATURE_CHESS_FAUNA_KEY=secret
      - CREATURE_CHESS_FAUNA_DOMAIN=faunadb
      - CREATURE_CHESS_FAUNA_SCHEME=http
      - CREATURE_CHESS_FAUNA_PORT=8443
    depends_on:
      - faunadb
    restart: always
  server-info:
    environment:
      - CREATURE_CHESS_FAUNA_KEY=secret
      - CREATURE_CHESS_FAUNA_DOMAIN=faunadb
      - CREATURE_CHESS_FAUNA_SCHEME=http
      - CREATURE_CHESS_FAUNA_PORT=8443
    depends_on:
      - faunadb
    restart: always
