version: "3.8"
services:
  # the postgres DB
  postgres:
    image: postgres:13.9
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 15s
      timeout: 5s
      start_period: 10s
      retries: 20
  # pgadmin, a local web UI for managing the DB
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 5050:80
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      postgres:
        condition: service_healthy
  # set up dependencies from the core apps onto this DB
  server-game:
    depends_on:
      postgres:
        condition: service_healthy
  server-info:
    depends_on:
      postgres:
        condition: service_healthy
