version: "3.8"
services:
  server-game:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - DISCORD_BOT_TOKEN
      - NODE_ENV=development
    build:
      context: .
      dockerfile: ./apps/server-game/Dockerfile
    ports:
      - "3000:3000"
  server-info:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - NODE_ENV=development
    build:
      context: .
      dockerfile: ./apps/server-info/Dockerfile
    ports:
      - "3001:3000"
