version: "3.8"
services:
  faunadb:
    image: fauna/faunadb
    volumes:
      - ./.faunadb/lib/:/var/lib/faunadb
      - ./.faunadb/log/:/var/log/faunadb
    ports:
      - 8443:8443
      - 8084:8084
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443"]
      interval: 30s
      timeout: 5s
      retries: 5
  nginx:
    build:
      context: .
      dockerfile: nginx/local-dev/Dockerfile
    volumes:
      - ./nginx/local-dev/nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/local-dev/nginx/access.log:/etc/nginx/access_log.log
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web-menu
      - server-game
      - server-info
  web-menu:
    environment:
      - DISCORD_BOT_TOKEN
      - AUTH0_DOMAIN
      - AUTH0_SPA_CLIENT_ID
      - CREATURE_CHESS_APP_URL
      - GAME_SERVER_URL
      - API_INFO_URL
      - NODE_ENV=development
    build:
      context: .
      dockerfile: apps/Dockerfile
      args:
        - APP_DIR=web-menu
    ports:
      - "3000"
    depends_on:
      - faunadb
  server-game:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - CREATURE_CHESS_FAUNA_DOMAIN
      - CREATURE_CHESS_FAUNA_SCHEME
      - CREATURE_CHESS_FAUNA_PORT
      - DISCORD_BOT_TOKEN
      - AUTH0_DOMAIN
      - AUTH0_SPA_CLIENT_ID
      - AUTH0_MACHINE_TO_MACHINE_CLIENT_ID
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - CREATURE_CHESS_APP_URL
      - NODE_ENV=development
    build:
      context: .
      dockerfile: apps/Dockerfile
      args:
        - APP_DIR=server-game
    ports:
      - "3000"
    depends_on:
      - faunadb
    restart: always
  server-info:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - CREATURE_CHESS_FAUNA_DOMAIN
      - CREATURE_CHESS_FAUNA_SCHEME
      - CREATURE_CHESS_FAUNA_PORT
      - AUTH0_DOMAIN
      - AUTH0_SPA_CLIENT_ID
      - AUTH0_MACHINE_TO_MACHINE_CLIENT_ID
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - CREATURE_CHESS_APP_URL
      - NODE_ENV=development
    build:
      context: .
      dockerfile: apps/Dockerfile
      args:
        - APP_DIR=server-info
    ports:
      - "3000"
    depends_on:
      - faunadb
    restart: always
