version: "3.8"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/access.log:/etc/nginx/access_log.log
    ports:
      - 8080:8080
  web-menu:
    build:
      context: .
      dockerfile: ./apps/web-menu/Dockerfile
    ports:
      - "8090:8090"
  server-game:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - DISCORD_BOT_TOKEN
      - NODE_ENV=development
    build:
      context: .
      dockerfile: ./apps/server-game/Dockerfile
    ports:
      - "3000:3000"
  server-info:
    environment:
      - CREATURE_CHESS_FAUNA_KEY
      - AUTH0_MANAGEMENT_CLIENT_SECRET
      - NODE_ENV=development
    build:
      context: .
      dockerfile: ./apps/server-info/Dockerfile
    ports:
      - "3001:3000"
