export const BENCH_PIECES_UPDATED = "BENCH_PIECES_UPDATED";
export type BENCH_PIECES_UPDATED = typeof BENCH_PIECES_UPDATED;

export const BENCH_PIECE_ADDED = "BENCH_PIECE_ADDED";
export type BENCH_PIECE_ADDED = typeof BENCH_PIECE_ADDED;
