export const REMOVE_BOARD_PIECE = "REMOVE_BOARD_PIECE";
export type REMOVE_BOARD_PIECE = typeof REMOVE_BOARD_PIECE;

export const ADD_BOARD_PIECE = "ADD_BOARD_PIECE";
export type ADD_BOARD_PIECE = typeof ADD_BOARD_PIECE;

export const INITIALISE_BOARD = "INITIALISE_BOARD";
export type INITIALISE_BOARD = typeof INITIALISE_BOARD;

export const UPDATE_BOARD_PIECE = "UPDATE_BOARD_PIECE";
export type UPDATE_BOARD_PIECE = typeof UPDATE_BOARD_PIECE;

export const UPDATE_BOARD_PIECES = "UPDATE_BOARD_PIECES";
export type UPDATE_BOARD_PIECES = typeof UPDATE_BOARD_PIECES;

export const MOVE_BOARD_PIECE = "MOVE_BOARD_PIECE";
export type MOVE_BOARD_PIECE = typeof MOVE_BOARD_PIECE;

export const LOCK_BOARD = "LOCK_BOARD";
export type LOCK_BOARD = typeof LOCK_BOARD;

export const UNLOCK_BOARD = "UNLOCK_BOARD";
export type UNLOCK_BOARD = typeof UNLOCK_BOARD;
