export const BEGIN_DRAG_BENCH_PIECE = "BEGIN_DRAG_BENCH_PIECE";
export type BEGIN_DRAG_BENCH_PIECE = typeof BEGIN_DRAG_BENCH_PIECE;

export const BEGIN_DRAG_BOARD_PIECE = "BEGIN_DRAG_BOARD_PIECE";
export type BEGIN_DRAG_BOARD_PIECE = typeof BEGIN_DRAG_BOARD_PIECE;

export const SELECT_PIECE = "SELECT_PIECE";
export type SELECT_PIECE = typeof SELECT_PIECE;
