export const FIND_GAME = "FIND_GAME";
export type FIND_GAME = typeof FIND_GAME;

export const JOIN_GAME = "JOIN_GAME";
export type JOIN_GAME = typeof JOIN_GAME;

export const CREATE_GAME = "CREATE_GAME";
export type CREATE_GAME = typeof CREATE_GAME;

export const JOIN_ERROR = "JOIN_ERROR";
export type JOIN_ERROR = typeof JOIN_ERROR;

export const GAME_PHASE_UPDATE = "GAME_PHASE_UPDATE";
export type GAME_PHASE_UPDATE = typeof GAME_PHASE_UPDATE;

export const MONEY_UPDATE = "MONEY_UPDATE";
export type MONEY_UPDATE = typeof MONEY_UPDATE;

export const PHASE_TIMER_UPDATED = "PHASE_TIMER_UPDATED";
export type PHASE_TIMER_UPDATED = typeof PHASE_TIMER_UPDATED;

export const ENABLE_DEBUG_MODE = "ENABLE_DEBUG_MODE";
export type ENABLE_DEBUG_MODE = typeof ENABLE_DEBUG_MODE;

export const UPDATE_ANNOUNCEMENT = "UPDATE_ANNOUNCEMENT";
export type UPDATE_ANNOUNCEMENT = typeof UPDATE_ANNOUNCEMENT;

export const CLEAR_ANNOUNCEMENT = "CLEAR_ANNOUNCEMENT";
export type CLEAR_ANNOUNCEMENT = typeof CLEAR_ANNOUNCEMENT;

export const SERVER_DISCONNECTED = "SERVER_DISCONNECTED";
export type SERVER_DISCONNECTED = typeof SERVER_DISCONNECTED;
