export const JOIN_LOBBY = "JOIN_LOBBY";
export type JOIN_LOBBY = typeof JOIN_LOBBY;

export const UPDATE_LOBBY_PLAYER = "UPDATE_LOBBY_PLAYER";
export type UPDATE_LOBBY_PLAYER = typeof UPDATE_LOBBY_PLAYER;