export const JOIN_LOBBY = "JOIN_LOBBY";
export type JOIN_LOBBY = typeof JOIN_LOBBY;

export const UPDATE_LOBBY_PLAYER = "UPDATE_LOBBY_PLAYER";
export type UPDATE_LOBBY_PLAYER = typeof UPDATE_LOBBY_PLAYER;

export const UPDATE_LOBBY_SECONDS_REMAINING = "UPDATE_LOBBY_SECONDS_REMAINING";
export type UPDATE_LOBBY_SECONDS_REMAINING = typeof UPDATE_LOBBY_SECONDS_REMAINING;

export const START_LOBBY_GAME = "START_LOBBY_GAME";
export type START_LOBBY_GAME = typeof START_LOBBY_GAME;
