export const JOIN_COMPLETE = "JOIN_COMPLETE";
export type JOIN_COMPLETE = typeof JOIN_COMPLETE;

export const LEVEL_UPDATE = "LEVEL_UPDATE";
export type LEVEL_UPDATE = typeof LEVEL_UPDATE;

export const UPDATE_RECONNECT_SECRET = "UPDATE_RECONNECT_SECRET";
export type UPDATE_RECONNECT_SECRET = typeof UPDATE_RECONNECT_SECRET;
