export const PLAYER_DROP_PIECE = "PLAYER_DROP_PIECE";
export type PLAYER_DROP_PIECE = typeof PLAYER_DROP_PIECE;

export const PLAYER_SELL_PIECE = "PLAYER_SELL_PIECE";
export type PLAYER_SELL_PIECE = typeof PLAYER_SELL_PIECE;
