export const BENCH_PIECE_MOVED = "BENCH_PIECE_MOVED";
export type BENCH_PIECE_MOVED = typeof BENCH_PIECE_MOVED;

export const BENCH_PIECES_UPDATED = "BENCH_PIECES_UPDATED";
export type BENCH_PIECES_UPDATED = typeof BENCH_PIECES_UPDATED;
