export const JOIN_COMPLETE = "JOIN_COMPLETE";
export type JOIN_COMPLETE = typeof JOIN_COMPLETE;

export const JOIN_GAME = "JOIN_GAME";
export type JOIN_GAME = typeof JOIN_GAME;

export const GAME_PHASE_UPDATE = "GAME_PHASE_UPDATE";
export type GAME_PHASE_UPDATE = typeof GAME_PHASE_UPDATE;

export const MONEY_UPDATE = "MONEY_UPDATE";
export type MONEY_UPDATE = typeof MONEY_UPDATE;

export const PIECE_SELECTED = "PIECE_SELECTED";
export type PIECE_SELECTED = typeof PIECE_SELECTED;

export const BANNER_UPDATED = "BANNER_UPDATED";
export type BANNER_UPDATED = typeof BANNER_UPDATED;

export const PHASE_TIMER_UPDATED = "PHASE_TIMER_UPDATED";
export type PHASE_TIMER_UPDATED = typeof PHASE_TIMER_UPDATED;
