export const PIECE_SELECTED = "PIECE_SELECTED";
export type PIECE_SELECTED = typeof PIECE_SELECTED;

export const PIECE_MOVED_TO_BOARD = "PIECE_MOVED_TO_BOARD";
export type PIECE_MOVED_TO_BOARD = typeof PIECE_MOVED_TO_BOARD;

export const PIECES_UPDATED = "PIECES_UPDATED";
export type PIECES_UPDATED = typeof PIECES_UPDATED;
