export const PIECE_MOVED_TO_BOARD = "PIECE_MOVED_TO_BOARD";
export type PIECE_MOVED_TO_BOARD = typeof PIECE_MOVED_TO_BOARD;

export const PIECE_MOVED_TO_BENCH = "PIECE_MOVED_TO_BENCH";
export type PIECE_MOVED_TO_BENCH = typeof PIECE_MOVED_TO_BENCH;

export const PIECES_UPDATED = "PIECES_UPDATED";
export type PIECES_UPDATED = typeof PIECES_UPDATED;
