name: Deploy menu to GitHub Pages

on:
  push:
    tags:
      - '*'

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false # needed for the GitHub Pages deploy to work
    - name: Use Node.js '16.x'
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: yarn
    - name: Build application
      run: yarn workspace @creature-chess/web-menu build
      env:
        GA_ID: ${{ secrets.GA_ID }}
        COOKIEBOT_ID: ${{ secrets.COOKIEBOT_ID }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        GAME_SERVER_URL: ${{ secrets.GAME_SERVER_URL }}
        API_INFO_URL: ${{ secrets.API_INFO_URL }}
        GH_PAGES: true
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.4.1
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: apps/web-menu/public
